apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.remixrender'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.remixrender"
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    compileSdkVersion safeExtGet("compileSdkVersion", 34)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }
  lintOptions {
    abortOnError false
  }
}
